# Generated by Django 4.2.2 on 2024-03-20 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignaciones_caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignacion', models.CharField(max_length=100)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='media/uploads')),
                ('campo_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fechalimite', models.DateField(blank=True, null=True)),
                ('prioridades', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('fechaInicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('detalleRelevantes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('campo_fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('casos', models.ManyToManyField(blank=True, through='modulos.Asignaciones_caso', to='modulos.caso')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenciaTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=100)),
                ('archivo_evidencia', models.FileField(blank=True, null=True, upload_to='media/evidencias')),
                ('campo_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fechalimite', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(max_length=100)),
                ('prioridades', models.CharField(max_length=100)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias_tarea', to='modulos.asignaciones_caso')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.miembro')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('campo_fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('casos', models.ManyToManyField(blank=True, through='modulos.Asignaciones_caso', to='modulos.caso')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Audiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.asignaciones_caso')),
            ],
        ),
        migrations.AddField(
            model_name='asignaciones_caso',
            name='casos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabla_intermedia_caso', to='modulos.caso'),
        ),
        migrations.AddField(
            model_name='asignaciones_caso',
            name='clientes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabla_intermedia_cliente', to='modulos.cliente'),
        ),
        migrations.AddField(
            model_name='asignaciones_caso',
            name='miembros',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabla_intermedia_miebro', to='modulos.miembro'),
        ),
    ]
