# Generated by Django 4.2.2 on 2024-03-20 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignaciones_caso',
            name='asignacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asignaciones_caso',
            name='casos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tabla_intermedia_caso', to='modulos.caso'),
        ),
        migrations.AlterField(
            model_name='asignaciones_caso',
            name='clientes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tabla_intermedia_cliente', to='modulos.cliente'),
        ),
        migrations.AlterField(
            model_name='asignaciones_caso',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asignaciones_caso',
            name='miembros',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tabla_intermedia_miebro', to='modulos.miembro'),
        ),
        migrations.AlterField(
            model_name='asignaciones_caso',
            name='prioridades',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='caso',
            name='detalleRelevantes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evidenciatarea',
            name='asignacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencias_tarea', to='modulos.asignaciones_caso'),
        ),
        migrations.AlterField(
            model_name='evidenciatarea',
            name='descripcion',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evidenciatarea',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evidenciatarea',
            name='prioridades',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
